spring:
  application:
    name: lab2
  datasource:
    url: jdbc:postgresql://localhost:5432/ilerijavayeni
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
      show-sql: true
  data:
      jdbc:
        dialect: postgresql
  messages:
    basename: messages
    cache-duration: 3600
    fallback-to-system-locale: true
    use-code-as-default-message: false
    always-use-message-format: false
springdoc:
  api-docs:
    path: /api-docs
server:
  port: 8080
